<#
.SYNOPSIS
    Deploys the Service Bus namespace used by the notebook walkthrough.

.EXAMPLE
    ./deploy.ps1 -ResourceGroup rg-sbdemo -Location eastus -NamespaceName sbdemo12345
#>
param(
    [Parameter(Mandatory = $true)] [string] $ResourceGroup,
    [Parameter(Mandatory = $true)] [string] $NamespaceName,
    [string] $Location = "eastus",
    [string] $Sku = "Standard",
    [string] $PrincipalId = ""
)

$ErrorActionPreference = "Stop"

Write-Host "Ensuring resource group '$ResourceGroup' exists in $Location..." -ForegroundColor Cyan
az group create -n $ResourceGroup -l $Location --output none

Write-Host "Deploying Bicep template..." -ForegroundColor Cyan
$deployment = az deployment group create `
    -g $ResourceGroup `
    -f (Join-Path $PSScriptRoot "main.bicep") `
    -p namespaceName=$NamespaceName location=$Location skuName=$Sku principalId=$PrincipalId `
    --query "properties.outputs" `
    -o json | ConvertFrom-Json

if (-not $deployment) {
    throw "Deployment failed."
}

$connString = $deployment.primaryConnectionString.value
$hostname   = $deployment.namespaceHostname.value

Write-Host ""
Write-Host "Deployment complete." -ForegroundColor Green
Write-Host "Namespace : $($deployment.namespaceName.value)"
Write-Host "Hostname  : $hostname"

# Write .env at the repo root so the notebooks pick it up automatically.
$repoRoot = Split-Path -Parent $PSScriptRoot
$envPath  = Join-Path $repoRoot ".env"

$envContents = @(
    "# Auto-generated by infra/deploy.ps1 on $(Get-Date -Format o)"
    "SERVICEBUS_CONNECTION_STRING=$connString"
    "SERVICEBUS_NAMESPACE=$hostname"
) -join [Environment]::NewLine

Set-Content -Path $envPath -Value $envContents -Encoding UTF8 -NoNewline

Write-Host ""
Write-Host "Wrote $envPath" -ForegroundColor Yellow
Write-Host "The notebooks will read this file automatically — no env vars needed."
